### ISSUE TITLE
Supported Java version

### ISSUE THREAD

**Issue by eugenio-quero** [dragon66/pixymeta#5]
Hi Dragon66,

I'm getting this error recently while invoking pixy.meta.MetadataMetadata.readMetadata(file):

java.lang.UnsupportedClassVersionError: pixy/meta/Metadata : Unsupported major.minor version 52.0

Does it mean that pixy does not support Java 1.7 anymore? 
Any help would be appreciated.

**Comment by dragon66** [comment]
@eugenio-quero source code wise, this library is java 5 compliant. I dad some difficulty building and deploying the lib to Maven and happened to have Java 8 setup at last build.

I guess you are using this lib through Maven otherwise, you could have build it yourself with lower java version. 

Will try to rebuild with Java 5 in next few days and comment on this issue to let you know.

Wen

**Comment by eugenio-quero** [comment]
Hi @dragon66,

Many thanks for your prompt response. Yes, I'm using pixy through Maven repo. As my project is Java 7 compilation, and you compiled with version 8,  the error now makes sense for me...

As a workaround I changed my pom.xml to force version 20170225.225747-73 and everything is working fine. But it would be great to have again the snapshot version compliant with  previous Java versions.

Thanks!

Eugenio
