### ISSUE TITLE
"Premature end of SOS segment" if trying to just read the headers

### ISSUE THREAD

**Issue by StefanOltmann** [dragon66/pixymeta#7]
For metadata parsing of cloud files I only download the JPEG header.

I can read the metadata of this file using https://github.com/drewnoakes/metadata-extractor and https://github.com/apache/commons-imaging

If I try to read this file with pixymeta I get an error:
```
Caused by: java.io.IOException: Premature end of SOS segment!
	at pixy.meta.jpeg.JPGMeta.readSOS(Unknown Source)
	at pixy.meta.jpeg.JPGMeta.readMetadata(Unknown Source)
	at pixy.meta.Metadata.readMetadata(Unknown Source)
```

Does this library try to read more than just the header? Why?

It would be way more efficient to stop reading from the inputStream when the section with header bytes are processed.

Here is a sample file:
[testphoto.jpg](https://user-images.githubusercontent.com/9299303/234284240-3e35812e-e448-4d8c-86e0-2c05fee60415.jpg)

**Comment by dragon66** [comment]
@StefanOltmann I am not sure what exactly you mean by header in the case of JPEG file. It is composed of different segments and there is no specific sequence for the segments to appear in the file except a few of them.

For this reason the lib will read at least when it sees there is a SOS segment to make sure not missing any metadata segments. Plus this lib is also used to remove, add, as well as change certain metadata and put everything back afterwards. So that's the reasons behind.

For extracting the metadata, I believe the SOS segment header itself is read not anything more but at least it is expected the lib can see that piece.

By the way how did you partially pull the image? Is the image a valid one to be actually displayed by image viewer?

Wen

**Comment by StefanOltmann** [comment]
@dragon66,

I have discovered that both metadata-extractor and Apache Commons Imaging only read the file up until they encounter the first Start of Scan (FF DA) segment. This approach is more efficient in terms of file processing.

Based on this observation, I assumed that the metadata block must be complete with the first FF DA segment. Is this correct?

To extract metadata from files stored on OneDrive, I download the file up until the SOS segment and only feed that segment into metadata-extractor. This method enables my photo application to display the full metadata of the cloud-hosted file without requiring the complete original file to be downloaded.

However, pixymeta reads all bytes of the file instead. I have altered my approach by adding a minimal SOS segment and the file end marker FF D9 to the bytes before feeding them into pixymeta. This method works for me.

**Comment by dragon66** [comment]
I looked a bit further into this issue and found the reason for this library to read beyond the first SOS. In a normal case, it is true to stop reading when the first SOS is encountered. But in hierarchical JPEG, reader would expect more than one SOF and SOS.

**Comment by dragon66** [comment]
@StefanOltmann As far as I can recall the reason for the current behavior is in some cases - hierarchical mode or something, there could be more SOS and SOF. For baseline JPEG reading to SOS should be enough. I may add some kind of options to the metadata reader to specify different read mode and change a bit of the metada reading mechanism to stop at the first SOS for your use case.

**Comment by StefanOltmann** [comment]
Okay, I see. Since this lib can also write I understand why it reads the whole file per default. Thank you for your explanation. I consider this to be resolved for now.
