### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by StefanOltmann** [dragon66/pixymeta#9]
I'm curious to know why you chose the EPL license instead of Apache 2. Also, what factors are important to you when someone forks your project?

**Comment by dragon66** [comment]
@StefanOltmann I think the reason is I found out EPL is less restrictive than Apache 2. My intention for this lib is the user can work with it wherever he/she wants especially no restrictions for commercial usage.

I know a few users who forked the project has adapted it to there own lib. If it is compatible with the original, I would expect a PR to enhance my project and these has been done before but not a lot. Also giving due credit to the author is very important as I have spent so much time on this for a totally free library.  Of course, I wouldn't mind if someone find it useful and buy me a beer. Up to now, that happened only once.

Furthermore, there are still quite a bit things need to be done to make this library more useful and I have no contributors besides me.
